# Generated by Django 4.0.1 on 2022-11-26 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='user_id')),
                ('subject_id', models.IntegerField(default=0, verbose_name='subject_id')),
                ('date_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_from')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
