# Generated by Django 4.0.1 on 2022-11-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='score1',
            field=models.IntegerField(default=0, verbose_name='score1'),
        ),
    ]
