# Generated by Django 4.0.1 on 2022-11-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_remove_grades_score_remove_grades_score1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='grade_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='grade_type'),
        ),
    ]
