# Generated by Django 4.0.1 on 2022-11-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_remove_grades_score_grades_grade_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='scores',
        ),
        migrations.AddField(
            model_name='grades',
            name='score',
            field=models.IntegerField(default=0, verbose_name='score'),
        ),
    ]
