# Generated by Django 4.0.1 on 2022-11-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_remove_grades_scores_grades_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
    ]
