# Generated by Django 4.0.1 on 2022-11-26 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_grades_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='date_from',
        ),
        migrations.AddField(
            model_name='grades',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_submitted'),
        ),
    ]
