# Generated by Django 4.0.1 on 2022-11-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_remove_grades_subject_id_grades_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='subject',
        ),
        migrations.AddField(
            model_name='grades',
            name='subject_id',
            field=models.IntegerField(default=0, verbose_name='subject_id'),
        ),
    ]
