# Generated by Django 4.0.1 on 2022-11-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_remove_grades_subject_grades_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='user_id',
        ),
    ]
