# Generated by Django 4.0.1 on 2022-11-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0010_remove_grades_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='user_id'),
        ),
    ]
