# Generated by Django 4.0.1 on 2022-11-26 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='user_id')),
                ('subject_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='subject_name')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
