# Generated by Django 4.0.1 on 2022-11-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='enrolled',
            name='subject_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject_id'),
        ),
    ]
