# Generated by Django 4.0.1 on 2022-11-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0002_remove_enrolled_subject_name_enrolled_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='subject_id',
            field=models.IntegerField(default=0, verbose_name='subject_id'),
        ),
    ]
