# Generated by Django 4.0.1 on 2022-10-15 13:41

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='subject_name')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_added')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
