# Generated by Django 4.0.1 on 2022-10-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='template',
            name='subject_id',
        ),
    ]
