# Generated by Django 4.0.1 on 2022-10-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_remove_template_date_added_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template',
            new_name='Subject',
        ),
    ]
