# Generated by Django 4.0.1 on 2022-11-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_rename_template_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='kinder_level',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='kinder_level'),
        ),
    ]
