# Generated by Django 4.0.1 on 2022-10-15 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True, verbose_name='firstname')),
                ('lastname', models.CharField(blank=True, max_length=255, null=True, verbose_name='lastname')),
                ('middlename', models.CharField(blank=True, max_length=255, null=True, verbose_name='middlename')),
                ('section', models.CharField(blank=True, max_length=255, null=True, verbose_name='section')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('date_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_from')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
